---
# file: roles/jkyle/tasks/main.yml

# Package Installation
- name: Install YUM Packages
  yum:  name={{ item }} state=latest
  when: ansible_os_family == "RedHat"
  sudo: yes
  with_items:
    - epel-release
    - bind-utils
    - zsh
    - git-core
    - lsof
    - tcpdump
    - vim
  tags: 
    - users
    - packages

- name: Install APT Packages
  apt: name={{ item }} state=latest
  when: ansible_os_family == "Debian"
  sudo: yes
  with_items:
      - apt-file
      - zsh
      - vim
      - git 
  tags:
      - users
      - packages

- name: Install Gentoo Packages
  portage: package={{ item }} state=present
  sudo: yes
  when: ansible_os_family == "Gentoo"
  with_items:
    - zsh
    - vim
    - git
    - ncurses

# I got the pip stuff from the bobbyrenwick/ansible-pip role 
# Thanks dude.
- name: check to see if pip is already installed
  command: "pip --version"
  ignore_errors: true
  changed_when: false
  register: pip_is_installed
  changed_when: false

- name: download pip
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp
  when: pip_is_installed.rc != 0

- name: install pip
  command: "python /tmp/get-pip.py"
  sudo: yes
  when: pip_is_installed.rc != 0

- name: Install Pip Packages
  pip: name={{ item }} state=present
  sudo: yes
  with_items:
    - virtualenvwrapper

- include: devtools.yml
- include: sciencetools.yml
# End Package Installation

- shell: which zsh
  register: zsh_path

- name: Create James
  user: name=jkyle
        uid={{ uid }}
        shell={{ zsh_path.stdout_lines[0] }}
  sudo: yes
  tags:
      - users
- name: Configure jkyle sudoers
  copy: src=sudoers dest=/etc/sudoers.d/jkyle owner=root group=root mode=0600
  sudo: yes
  tags:
      - users

- name: Deploy jkyle User Key
  authorized_key: user=jkyle key="{{ lookup('file', 'att_rsa.pub') }}"
  tags:
      - users

- name: Setup James Home Directory
  git: repo=https://jkyle@bitbucket.org/jkyle/prezto.git
       dest=/home/jkyle/.zprezto
       version=develop
       force=yes
  tags:
      - users

- name: Link James configuration files
  file: src=/home/jkyle/.zprezto/runcoms/{{ item }} 
        dest=/home/jkyle/.{{ item }} 
        state=link
        force=yes
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc
  tags:
      - users
