- name: Install YUM Science Tools Group
  yum:  name={{ item }} state=latest
  when: ansible_os_family == "RedHat" and sciencetools
  sudo: yes
  with_items:
    - R

- name: Install APT Science Tools Packages
  apt: name={{ item }} state=latest
  when: ansible_os_family == "Debian" and sciencetools
  sudo: yes
  with_items:
    - r-base
    - r-base-dev

