---
# file: roles/jkyle/tasks/main.yml

# Package Installation
- include: packages/redhat.yml
  when: packages|bool and ansible_os_family == "RedHat"

- include: packages/debian.yml
  when: packages|bool and ansible_os_family == "Debian"

- include: packages/debian.yml
  when: packages|bool and ansible_os_family == "Gentoo"

# End Package Installation

# Begin User Configuration
- include: user.yml
  when: user_config|bool
  # End User Configuration

- name: Deploy User Public Key
  authorized_key: user="{{ username }}" key="{{ pubkey }}"
  when: deploy_pubkey|bool

- name: Setup James Home Directory
  git: repo=https://jkyle@bitbucket.org/jkyle/prezto.git
       dest="/home/{{ username }}/.zprezto"
       version="{{ zprezto_version }}"
       force=yes

- name: Link James configuration files
  file: src="/home/{{ username }}/.zprezto/runcoms/{{ item }}"
        dest="/home/{{ username }}/.{{ item }}"
        state=link
        force=yes
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc
